# Generated by Django 4.2.3 on 2023-07-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
