# Generated by Django 4.2.3 on 2023-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcake', '0002_rename_firstname_tbl_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('flavour', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'tbl_cake',
            },
        ),
    ]
